<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gpsnose"
 *
 * Auto generated by Extension Builder 2018-04-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'GpsNose',
    'description' => 'Extension to integrate GpsNose into TYPO3',
    'category' => 'plugin',
    'author' => 'dev',
    'author_email' => 'dev@gpsnose.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
