<?php
return [
    'tools_GpsnoseGnadmin' => [
        'parent' => 'tools',
        'access' => 'admin',
        'iconIdentifier' => 'gpsnose-gnadmin-module',
        'path' => '/module/web/GpsnoseGnadmin',
        'labels' => 'LLL:EXT:gpsnose/Resources/Private/Language/locallang_gnadmin.xlf',
        'extensionName' => 'Gpsnose',
        'controllerActions' => [
            \SmartNoses\Gpsnose\Controller\MashupController::class => [
                'start',
                'login',
                'loginVerifie',
                'keepAlive',
                'logout',
                'relogin',
                'refresh',
                'list',
                'show',
                'new',
                'create',
                'validate',
                'edit',
                'addSubCommunity',
                'removeSubCommunity',
                'addHost',
                'removeHost',
                'regenerateAppKey',
                'updateCallbackUrl',
                'delete',
                'tokenlist',
                'tokenshow',
                'tokenrefresh',
                'tokennew',
                'tokencreate',
                'tokenedit',
                'tokenupdate',
                'tokendelete',
            ],
        ],
    ],
];