services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  SmartNoses\Gpsnose\Domain\Repository\:
    resource: '../Classes/Domain/Repository/*'

  SmartNoses\Gpsnose\Controller\:
    resource: '../Classes/Controller/*'
